name:                socks5-proxy
version:             0.1.0.0
github:              "oshmkufa2010/socks5-proxy"
license:             BSD3
author:              "cailin"
maintainer:          "cailinunix@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oshmkufa2010/socks5-proxy#readme>

dependencies:
- base
- network
- bytestring
- mtl
- async
- network-simple
- exceptions
- stm
- containers

library:
  source-dirs: src

executables:
  socks5-proxy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - socks5-proxy

tests:
  socks5-proxy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - socks5-proxy
